/* AUTO-GENERATED by tools/gen_int_fft_table.py — do not edit by hand.
 * Regenerate: python3 tools/gen_int_fft_table.py 32
 *
 * Lifting-scheme twiddle LUT for the integer-to-integer FFT.
 * Coefficients are Q14 fixed-point (1.0 == 16384).
 *
 * Entry t encodes the rotation W_t = [[c,-s],[s,c]] with
 * angle t = -2*pi*t/32 for t = 0..15.
 * Type A: W = L3 L2 L1   (cos >= 0, three lifting shears)
 * Type B: W = -L3 L2 L1  (cos < 0, negate after lifting)
 *
 * Lifting steps (forward, all rounding via >> Q right shift):
 *   x += (q1*y) >> Q;  y += (q2*x) >> Q;  x += (q3*y) >> Q
 * Inverse applies the same coefficients in reverse order with
 * subtraction — the identical rounding guarantees exact
 * reconstruction (vault signal-processing/2026-05-31-integer-fft-lifting-scheme).
 */

#ifndef INT_FFT_LUT_H_
#define INT_FFT_LUT_H_

#include <stdint.h>

typedef struct {
    int16_t q1;     /* Q14 lifting coefficient, step 1 */
    int16_t q2;     /* Q14 lifting coefficient, step 2 */
    int16_t q3;     /* Q14 lifting coefficient, step 3 */
    uint8_t negate; /* 1 = Type B: negate result after lifting */
} int_fft_twiddle_t;

#define INT_FFT_LUT_SIZE 16

static const int_fft_twiddle_t int_fft_lut[INT_FFT_LUT_SIZE] = {
    /* t=0: identity (skip rotation) q1=0 q2=0 q3=0 */
    {0, 0, 0, 0},
    /* t=1: theta=-2*pi*1/32, Type A q1=1614 q2=-3196 q3=1614 */
    {1614, -3196, 1614, 0},
    /* t=2: theta=-2*pi*2/32, Type A q1=3259 q2=-6270 q3=3259 */
    {3259, -6270, 3259, 0},
    /* t=3: theta=-2*pi*3/32, Type A q1=4970 q2=-9102 q3=4970 */
    {4970, -9102, 4970, 0},
    /* t=4: theta=-2*pi*4/32, Type A q1=6786 q2=-11585 q3=6786 */
    {6786, -11585, 6786, 0},
    /* t=5: theta=-2*pi*5/32, Type A q1=8757 q2=-13623 q3=8757 */
    {8757, -13623, 8757, 0},
    /* t=6: theta=-2*pi*6/32, Type A q1=10947 q2=-15137 q3=10947 */
    {10947, -15137, 10947, 0},
    /* t=7: theta=-2*pi*7/32, Type A q1=13446 q2=-16069 q3=13446 */
    {13446, -16069, 13446, 0},
    /* t=8: theta=-2*pi*8/32, Type A q1=16384 q2=-16384 q3=16384 */
    {16384, -16384, 16384, 0},
    /* t=9: theta=-2*pi*9/32, Type B q1=-13446 q2=16069 q3=-13446 NEGATE */
    {-13446, 16069, -13446, 1},
    /* t=10: theta=-2*pi*10/32, Type B q1=-10947 q2=15137 q3=-10947 NEGATE */
    {-10947, 15137, -10947, 1},
    /* t=11: theta=-2*pi*11/32, Type B q1=-8757 q2=13623 q3=-8757 NEGATE */
    {-8757, 13623, -8757, 1},
    /* t=12: theta=-2*pi*12/32, Type B q1=-6786 q2=11585 q3=-6786 NEGATE */
    {-6786, 11585, -6786, 1},
    /* t=13: theta=-2*pi*13/32, Type B q1=-4970 q2=9102 q3=-4970 NEGATE */
    {-4970, 9102, -4970, 1},
    /* t=14: theta=-2*pi*14/32, Type B q1=-3259 q2=6270 q3=-3259 NEGATE */
    {-3259, 6270, -3259, 1},
    /* t=15: theta=-2*pi*15/32, Type B q1=-1614 q2=3196 q3=-1614 NEGATE */
    {-1614, 3196, -1614, 1},
};

#endif /* INT_FFT_LUT_H_ */
