#!/usr/bin/env python3
"""Generate the lifting-scheme twiddle LUT for the Phase Engine integer FFT.

Implements the rotation-matrix factorization from fukuroder's Qiita article
(vault: signal-processing/2026-05-31-integer-fft-lifting-scheme, based on
Oraintara, Chen, Nguyen 2002):

    Type A (cos t >= 0, -pi/2 <= t < 0):
        W_t = [[1,(c-1)/s],[0,1]] x [[1,0],[s,1]] x [[1,(c-1)/s],[0,1]]
    Type B (cos t < 0, -pi < t <= -pi/2):
        W_t = -[[1,(c+1)/s],[0,1]] x [[1,0],[-s,1]] x [[1,(c+1)/s],[0,1]]

Coefficients are quantized to Q14 (2^14 scale) so that |q| = 1.0 fits in
int16 (Q15 would overflow for the -pi/2 twiddle where q1 = 1.0 exactly).

The same quantized coefficients are used in the inverse transform with the
identical right-shift truncation, which makes the round trip structurally
exact regardless of coefficient precision (vault Finding 1).

Output: lib/phase/int_fft_lut.h (committed so the firmware build needs no
Python). Regenerate with: python3 tools/gen_int_fft_table.py

Usage: python3 tools/gen_int_fft_table.py [max_n]
"""

import math
import sys

MAX_N = int(sys.argv[1]) if len(sys.argv) > 1 else 32
Q = 14  # Q14 scale: 1.0 == 16384, fits int16
LUT_SIZE = MAX_N // 2


def q14(x: float) -> int:
    """Quantize a coefficient to Q14 with round-half-away-from-zero."""
    scaled = x * (1 << Q)
    if scaled >= 0:
        return int(scaled + 0.5)
    return int(scaled - 0.5)


def build_lut():
    entries = []
    for t in range(LUT_SIZE):
        theta = -2.0 * math.pi * t / MAX_N
        c = math.cos(theta)
        s = math.sin(theta)
        if t == 0:
            # Identity twiddle (theta = 0): s = 0 makes the factorization
            # degenerate; emit a zero entry and let the butterfly skip it.
            entries.append({"q1": 0, "q2": 0, "q3": 0, "negate": 0, "type": "A"})
            continue
        if c >= 0.0:
            # Type A
            q1 = (c - 1.0) / s
            q2 = s
            q3 = (c - 1.0) / s
            negate = 0
            typ = "A"
        else:
            # Type B: W = -L3 L2 L1
            q1 = (c + 1.0) / s
            q2 = -s
            q3 = (c + 1.0) / s
            negate = 1
            typ = "B"
        entries.append(
            {
                "q1": q14(q1),
                "q2": q14(q2),
                "q3": q14(q3),
                "negate": negate,
                "type": typ,
            }
        )
    return entries


def emit_header(entries):
    lines = []
    lines.append("/* AUTO-GENERATED by tools/gen_int_fft_table.py — do not edit by hand.")
    lines.append(f" * Regenerate: python3 tools/gen_int_fft_table.py {MAX_N}")
    lines.append(" *")
    lines.append(" * Lifting-scheme twiddle LUT for the integer-to-integer FFT.")
    lines.append(" * Coefficients are Q14 fixed-point (1.0 == 16384).")
    lines.append(" *")
    lines.append(" * Entry t encodes the rotation W_t = [[c,-s],[s,c]] with")
    lines.append(f" * angle t = -2*pi*t/{MAX_N} for t = 0..{LUT_SIZE - 1}.")
    lines.append(" * Type A: W = L3 L2 L1   (cos >= 0, three lifting shears)")
    lines.append(" * Type B: W = -L3 L2 L1  (cos < 0, negate after lifting)")
    lines.append(" *")
    lines.append(" * Lifting steps (forward, all rounding via >> Q right shift):")
    lines.append(" *   x += (q1*y) >> Q;  y += (q2*x) >> Q;  x += (q3*y) >> Q")
    lines.append(" * Inverse applies the same coefficients in reverse order with")
    lines.append(" * subtraction — the identical rounding guarantees exact")
    lines.append(" * reconstruction (vault signal-processing/2026-05-31-integer-fft-lifting-scheme).")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef INT_FFT_LUT_H_")
    lines.append("#define INT_FFT_LUT_H_")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    int16_t q1;     /* Q14 lifting coefficient, step 1 */")
    lines.append("    int16_t q2;     /* Q14 lifting coefficient, step 2 */")
    lines.append("    int16_t q3;     /* Q14 lifting coefficient, step 3 */")
    lines.append("    uint8_t negate; /* 1 = Type B: negate result after lifting */")
    lines.append("} int_fft_twiddle_t;")
    lines.append("")
    lines.append(f"#define INT_FFT_LUT_SIZE {LUT_SIZE}")
    lines.append("")
    lines.append("static const int_fft_twiddle_t int_fft_lut[INT_FFT_LUT_SIZE] = {")
    for t, e in enumerate(entries):
        comment = f"    /* t={t}: theta=-2*pi*{t}/{MAX_N}, Type {e['type']}"
        if t == 0:
            comment = f"    /* t={t}: identity (skip rotation)"
        lines.append(
            f"{comment} q1={e['q1']} q2={e['q2']} q3={e['q3']}"
            f"{' NEGATE' if e['negate'] else ''} */"
        )
        lines.append(
            f"    {{{e['q1']}, {e['q2']}, {e['q3']}, {e['negate']}}},"
        )
    lines.append("};")
    lines.append("")
    lines.append("#endif /* INT_FFT_LUT_H_ */")
    return "\n".join(lines) + "\n"


def main():
    entries = build_lut()
    out = emit_header(entries)
    path = "lib/phase/int_fft_lut.h"
    with open(path, "w") as f:
        f.write(out)
    print(f"Wrote {path}: {MAX_N}-point max, {LUT_SIZE} LUT entries")
    for t, e in enumerate(entries):
        print(
            f"  t={t:2d} type={e['type']} q1={e['q1']:6d} q2={e['q2']:6d} "
            f"q3={e['q3']:6d} negate={e['negate']}"
        )


if __name__ == "__main__":
    main()
